#!/bin/sh

alias ...="../../"
alias ....="../../../"
alias .....="../../../../"
alias ......="../../../../../"
alias ls="ls -p --color=auto --group-directories-first "
alias ll="ls -al"
alias la="ls -A"
alias l="ls -lA"
alias t="tree"
alias _="sudo"
alias s="sudo"
alias mkdir="mkdir -pv"
alias md="mkdir -pv"
alias rd="rmdir"
alias ka="killall"
alias x="exit"
alias c="clear"
alias b="bat"
alias v="vim"
alias nv="nvim"
alias tm="tmux"
alias z="zathura"
alias calcurse="calcurse -D ~/.config/calcurse"
alias ccs="calcurse"
alias g="git"
alias config="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias cg="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias y="youtube-dl"
alias yd='youtube-dl --format "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]"'
alias ydv='youtube-dl --format "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]" --default-search ytsearch'
alias yda='youtube-dl --format "bestaudio[ext=m4a]" --default-search ytsearch -x'
alias grep="grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}"
alias lg="lazygit"
alias ld="lazydocker"

alias f="l | grep"

alias ff='fzf --height 100% --preview "bat --width 70% --style=numbers --color=always --line-range :500 {}"'

ef() {
  FILE=$(fzf --height 100% --preview "bat --width 70% --style=numbers --color=always --line-range :500 {}")
  [ ! -z $FILE ] && $EDITOR $FILE
}

alias clock='while true; do clear; echo "==========="; date +"%r"; echo "==========="; sleep 1; done'

alias h="history | grep"

# Make [p]arent directories and [t]ouch file
pt() {
  [ -z "$1" ] && return 1
  mkdir -p "$(dirname "$1")"
  touch "$1"
}

colors() {
  for i in {0..255}; do  printf "\x1b[38;5;${i}mcolor%-5i\x1b[0m" $i ; if ! (( ($i + 1 ) % 8 )); then echo ; fi ; done
}

### GIT

alias ga='git add'
alias gb='git branch'
alias gd='git diff'
alias gl='git log'
alias gm='git merge'
alias gc='git checkout'
alias gs='git status'
alias gcg='git config'
alias gcm='git commit'
alias gcl='git clone'
alias gsh='git show'
alias gsw='git switch'
alias gpull='git pull'
alias gpush='git push'

alias gec='git config --global -e'
alias glast='git log -1 HEAD'

alias glp="git log --all --graph --abbrev-commit --date=relative --pretty=format:'%C(red)%h%Creset -%C(auto)%d%Creset %s %C(cyan)(%cr)%Creset'"
alias gls='git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate'
alias gll='git log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
alias gld='git log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=relative'
alias gldl='git log --pretty=format:"%C(yellow)%h\\ %ad%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --date=short'
