abbrev-alias ...='../../'
abbrev-alias ....='../../../'
abbrev-alias .....='../../../../'
abbrev-alias ......='../../../../../'
abbrev-alias t="tree"
abbrev-alias _='sudo'
abbrev-alias s='sudo'
abbrev-alias md='mkdir -pv'
abbrev-alias rd='rmdir'
abbrev-alias ka='killall'
abbrev-alias x='exit'
abbrev-alias c='clear'
abbrev-alias b='bat'
abbrev-alias v='vim'
abbrev-alias nv='nvim'
abbrev-alias tm='tmux'
abbrev-alias z='zathura'
abbrev-alias ccs='calcurse'
abbrev-alias g='git'
abbrev-alias cg='config'
abbrev-alias y='youtube-dl'
abbrev-alias yd='youtube-dl --format "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]"'
abbrev-alias ydv='youtube-dl --format "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]" --default-search ytsearch'
abbrev-alias yda='youtube-dl --format "bestaudio[ext=m4a]" --default-search ytsearch -x'
abbrev-alias rt='rtouch'
abbrev-alias lg='lazygit'
abbrev-alias ld='lazydocker'

### GIT

abbrev-alias ga='git add'
abbrev-alias gb='git branch'
abbrev-alias gd='git diff'
abbrev-alias gl='git log'
abbrev-alias gm='git merge'
abbrev-alias gc='git checkout'
abbrev-alias gs='git status'
abbrev-alias gcg='git config'
abbrev-alias gcm='git commit'
abbrev-alias gcl='git clone'
abbrev-alias gsh='git show'
abbrev-alias gsw='git switch'
abbrev-alias gpull='git pull'
abbrev-alias gpush='git push'

abbrev-alias gec='git config --global -e'
abbrev-alias glast='git log -1 HEAD'
