#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d '' '' '' '' '' '' '' '' '' ''

# bspc config normal_border_color  '#0000FF'
bspc config active_border_color  '#0000FF'
bspc config focused_border_color '#0000FF'
bspc config border_width            2
# bspc config window_gap             12
bspc config window_gap             0
bspc config split_ratio          0.52

# # focus_follows_pointer seems to break drag and drop actions
# bspc config focus_follows_pointer   true
# bspc config pointer_follows_focus   true
# bspc config pointer_follows_monitor true

# # Open nodes up instead of down and left instead of right
# bspc config initial_polarity first_child

# Master window layout
bspc config automatic_scheme spiral

# # Smart gaps and smart borders
bspc config single_monocle       true
bspc config borderless_monocle   true
# bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

killall auto_set_wall

picom --backend xrender &
dunst &
xset r rate 300 35 &
xautolock -detectsleep -corners 0-00 -time 5 -locker "$LOCK" -notify 30 -notifier "notify-send 'Locking screen in 30 seconds'" &
auto_set_wall &
$HOME/.config/polybar/launch &
xrandr --output LVDS --primary --mode 1366x768 --pos 0x629 --rotate normal --output HDMI-0 --mode 1920x1080 --pos 1366x0 --rotate normal --output VGA-0 --off &
nm-applet &
kitty sh -c 'tmux' &
