#!/bin/sh

for i in $(seq 1 $(bspc query -M | wc -l))
do
  bspc monitor "^$i" -d '' '' '' '' '' '' '' '' '' ''
done

bspc config normal_border_color  '#30302f'
bspc config active_border_color '#30302f'
bspc config focused_border_color  '#7199FF'
bspc config border_width            2
bspc config window_gap             0
bspc config split_ratio          0.52

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true

bspc config automatic_scheme spiral

bspc config single_monocle       true
bspc config borderless_monocle   true

# Use xprop and click on a window to see its WM_CLASS value
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv state=floating center=true
bspc rule -a feh state=floating center=true
bspc rule -a Gpick state=floating center=true
bspc rule -a Arandr state=floating center=true

startup
