#!/bin/bash
POWER_MENU_OPTIONS=('lock screen' 'logout' 'reboot' 'shutdown' 'cancel')

ACTION=$(
for index in "${!POWER_MENU_OPTIONS[@]}"
do
    echo ${POWER_MENU_OPTIONS[$index]}
done | rofi -i -dmenu -lines 5 -p 'Power Menu: ' -theme '/usr/share/rofi/themes/dmenu.rasi' -matching 'fuzzy'
)

ACTION=$( echo "${ACTION}" | sed -r 's/^\s+//;s/\s+$//' )

case $ACTION in
    '')
        exit 0
        ;;
    'lock screen')
        betterlockscreen -l dim
        ;;
    'logout')
        [ "$(printf "No\\nYes" | rofi -i -dmenu -p "Exit bspwm?" -theme /usr/share/rofi/themes/dmenu.rasi)" = "Yes" ] && bspc quit
        ;;
    'shutdown')
        [ "$(printf "No\\nYes" | rofi -i -dmenu -p "Shutdown?" -theme /usr/share/rofi/themes/dmenu.rasi)" = "Yes" ] && shutdown now
        ;;
    'cancel')
        exit 0
        ;;
    *)
        notify-send "${ACTION} - Action not defined"
        ;;
esac
