#!/bin/sh

killall set-wallpaper > /dev/null
killall picom > /dev/null

picom &
set-monitor &
set-wallpaper &
set-autolock &
dunst &
# xset r rate 120 100 &
xset r rate 300 50 &
nm-applet &

pgrep -x sxhkd > /dev/null

if [ $DESKTOP_SESSION = "bspwm" ]; then
  mkfifo /tmp/sfifo
  sxhkd -s '/tmp/sfifo' &
  sxhkd -s '/tmp/sfifo' -c $HOME/.config/bspwm/sxhkdrc &
  killall bspwm-mode > /dev/null
  bspwm-mode &
  $HOME/.config/polybar/launch &
else
  sxhkd &
fi
